import "@/styles/globals.css";
import localFont from "next/font/local";
import Navigation from "@/components/MainLayout/navbar";
import DesktopTopNavFixed from "@/components/MainLayout/desktop-topnav-fix";

const customFont = localFont({src: "../../public/fonts/Poppins-Medium.ttf"});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${customFont.className} antialiased bg-dark-customer md:flex overflow-y-hidden`}>
        <Navigation />
        <div className="w-full relative overflow-y-scroll">
        <DesktopTopNavFixed/>
        {children}
        </div>
      </body>
    </html>
  );
}
